#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "🔧 Initramfs: locating root filesystem..."

mkdir -p /newroot
mount /dev/sda /newroot

echo "🚀 Switching to real root..."

exec switch_root /newroot /init

