#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

# Set hostname
hostname "$(cat /etc/hostname)"

echo
echo "🌌 NebulaOS v0.1"
echo "System booted successfully."
echo

exec /bin/sh
